
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name goapi
  labels: &labels
    app: *service-name
spec:
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: testserviceaccount
      containers:
        - name: *service-name
          image: emailtovamos/goapi:v1
          command: ["./binary"]