kind: ServiceAccount
apiVersion: v1
metadata:
  name: testserviceaccount
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: testrole
rules:
  - apiGroups: [""]
    resources: ["services", "roles", "clusterroles"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testrole
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: testserviceaccount
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: testrole
  apiGroup: rbac.authorization.k8s.io